workflows:
  ios-workflow:
    name: iOS Build for SmartCent
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Setup iOS configuration
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            echo "Creating Podfile..."
            flutter pub get
          fi
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          echo "=== Building IPA manually ==="
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner.ipa Payload/
          cd ../../..
          echo "=== Checking for generated files ==="
          find . -name "*.ipa" -type f
          ls -la *.ipa || echo "No .ipa files in root"
          ls -la build/ios/ || echo "build/ios/ not found"
    artifacts:
      - "*.ipa"
      - build/ios/archive/*.xcarchive 