workflows:
  ios-workflow:
    name: iOS Build for SmartCent
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Setup iOS configuration
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            echo "Creating Podfile..."
            flutter pub get
          fi
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa 