workflows:
  ios-workflow:
    name: iOS Build for SmartCent
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: ad_hoc  # For testing/distribution
        bundle_identifier: com.example.ibs
    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Setup iOS configuration
        script: |
          cd ios
          if [ ! -f Podfile ]; then
            echo "Creating Podfile..."
            flutter pub get
          fi
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --export-method=ad-hoc
          echo "=== Checking for generated files ==="
          find . -name "*.ipa" -type f
          ls -la build/ios/ipa/ || echo "build/ios/ipa/ not found"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive 